### ISSUE TITLE
Problem with selective_search.py when setting cmd as 'selective_search_rcnn'

### ISSUE THREAD

**Issue by imbinwang** [sergeyk/selective_search_ijcv_with_python#15]
I am trying to run the demo _selective_search.py_. It generated boxes when I used the default value `'selective_search'` for optional argument `cmd`. However when I changed the optional argument as `cmd='selective_search_rcnn'`, it didn't work and gave following error message:

> Traceback (most recent call last):
>   File "selective_search_wb.py", line 63, in <module>
>     boxes = get_windows(image_filenames)
>   File "selective_search_wb.py", line 42, in get_windows
>     all_boxes = list(scipy.io.loadmat(output_filename)['all_boxes'][0])
>   File "/home/hy/capy/local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 134, in loadmat
>     MR = mat_reader_factory(file_name, appendmat, **kwargs)
>   File "/home/hy/capy/local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 58, in mat_reader_factory
>     mjv, mnv = get_matfile_version(byte_stream)
>   File "/home/hy/capy/local/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 224, in get_matfile_version
>     raise MatReadError("Mat file appears to be empty")
> scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty.

I had checked the temporary Mat file, it was indeed empty. Why did the parameter `cmd='selective_search_rcnn'` not generate boxes? How should I fix it?

Thanks  ~

**Comment by aelnouby** [comment]
@imbinwang Have you fixed this problem, may you tell me how if you had ?

**Comment by acgtyrant** [comment]
@imbinwang Me too...

**Comment by aelnouby** [comment]
@acgtyrant I downloaded the original matlab code of the authors then I pasted the different files there (selective_search.m, selective_search_rcnn.m , selective_search.py), it worked correctely there , yet I have no idea what was the problem and why it was fixed by this

**Comment by imbinwang** [comment]
@aelnouby @acgtyrant Sorry, the problem is still there for me. I ran the `selective_search.py` under py2.7 + MatlabR2014a + Ubuntu14.04. And I just changed the method `get_windows` as follows

> `def get_windows(image_fnames, cmd='selective_search')` to 
> `def get_windows(image_fnames, cmd='selective_search_rcnn')`

@aelnouby Did you find any difference between the matlab code in this repo and the original code?

**Comment by aelnouby** [comment]
@imbinwang  Actually I don't know, it just I have been using the matlab code previously so I thought I should give it a try and it worked !. I think you might want to try the demo.m first see if it works correctly then the matlab code is fine, it didn't work for me when i tried it for files of this repo.

**Comment by MaticDiba** [comment]
The problem is, that the executing line of the code, that calls matlab script, doesn't wait for it to end. So the file is generated, but not yet finished. The simplest way is to put a timer after the python line, which calls the matlab script.
